import { StyleSheet } from 'react-native';

import { BottomTabInset, MaxContentWidth, Spacing } from '@/constants/theme';

const sky = '#0EA5E9';
const skySoft = '#E0F2FE';
const skyBorder = '#BAE6FD';

export const myChoiceStyles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.three,
  },
  networkPage: {
    flex: 1,
    alignSelf: 'center',
    width: '100%',
    maxWidth: MaxContentWidth,
    justifyContent: 'center',
    padding: Spacing.three,
  },
  content: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: MaxContentWidth,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    paddingBottom: 108,
    gap: Spacing.three,
  },
  authKeyboard: { flex: 1 },
  authHero: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.four,
    gap: Spacing.three,
  },
  authCard: {
    borderRadius: 18,
    padding: Spacing.three,
    gap: Spacing.three,
    borderWidth: 1,
    borderColor: skyBorder,
  },
  segmentedControl: {
    flexDirection: 'row',
    borderRadius: 14,
    padding: Spacing.one,
    gap: Spacing.one,
  },
  segmentButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.two,
  },
  segmentButtonActive: { backgroundColor: sky },
  segmentTextActive: { color: '#FFFFFF' },
  logoMark: {
    width: 64,
    height: 64,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: sky,
  },
  logoText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
  },
  authLogo: {
    width: 78,
    height: 78,
    borderRadius: 22,
  },
  authTitle: {
    fontSize: 32,
    lineHeight: 40,
  },
  authCopy: {
    fontSize: 14,
    lineHeight: 22,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.three,
    paddingTop: Spacing.two,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  section: { gap: Spacing.three },
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.three,
  },
  pageTitle: {
    fontSize: 24,
    lineHeight: 32,
  },
  muted: { opacity: 0.72 },
  statusText: { color: '#E43D12' },
  skeletonBlock: {
    opacity: 0.62,
    overflow: 'hidden',
  },
  skeletonStack: {
    gap: Spacing.two,
    flex: 1,
  },
  skeletonLine: {
    width: 112,
    height: 14,
    borderRadius: 7,
  },
  skeletonWideLine: {
    width: '82%',
    height: 14,
    borderRadius: 7,
  },
  skeletonShortLine: {
    width: 74,
    height: 12,
    borderRadius: 6,
  },
  skeletonTitleLine: {
    width: 148,
    height: 22,
    borderRadius: 11,
  },
  skeletonPageTitle: {
    width: 132,
    height: 30,
    borderRadius: 15,
  },
  skeletonIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  skeletonHeroCard: {
    width: '100%',
    aspectRatio: 4 / 5,
    borderRadius: 18,
  },
  skeletonPanel: {
    borderRadius: 18,
    padding: Spacing.three,
    gap: Spacing.three,
    borderWidth: 1,
    borderColor: skyBorder,
  },
  skeletonButton: {
    width: 132,
    height: 44,
    borderRadius: 14,
  },
  skeletonButtonFull: {
    width: '100%',
    height: 50,
    borderRadius: 16,
  },
  skeletonFilter: {
    width: 116,
    minHeight: 46,
    borderRadius: 14,
  },
  skeletonHistoryLine: {
    width: '74%',
    height: 18,
    borderRadius: 9,
  },
  networkPanel: {
    borderRadius: 18,
    padding: Spacing.four,
    gap: Spacing.two,
    borderWidth: 1,
    borderColor: skyBorder,
    alignItems: 'flex-start',
  },
  networkCopy: {
    lineHeight: 21,
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: sky,
    paddingHorizontal: Spacing.four,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.two,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  googleButton: {
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: skyBorder,
    paddingHorizontal: Spacing.four,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.two,
  },
  googleButtonText: {
    fontSize: 14,
    fontWeight: '800',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: skyBorder,
  },
  secondaryButton: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: skyBorder,
    paddingHorizontal: Spacing.four,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: { color: sky },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: sky,
  },
  featureCard: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: skyBorder,
  },
  compactFeature: { flexDirection: 'row' },
  featureImage: {
    width: '100%',
    aspectRatio: 4 / 5,
  },
  compactFeatureImage: {
    width: 92,
    height: 116,
  },
  featureText: {
    padding: Spacing.three,
    gap: Spacing.one,
    flex: 1,
  },
  featureTitle: {
    fontSize: 18,
    lineHeight: 25,
  },
  emptyPanel: {
    borderRadius: 18,
    padding: Spacing.four,
    gap: Spacing.three,
    borderWidth: 1,
    borderColor: skyBorder,
  },
  emptyTitle: {
    fontSize: 18,
    lineHeight: 25,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthTitle: {
    fontSize: 18,
    lineHeight: 26,
    textAlign: 'center',
    flex: 1,
  },
  weekRow: { flexDirection: 'row' },
  weekDay: {
    width: `${100 / 7}%`,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: skyBorder,
  },
  dayCell: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: skyBorder,
    gap: Spacing.one,
  },
  dimmedDay: { opacity: 0.35 },
  selectedDay: { backgroundColor: sky },
  selectedDayText: { color: '#FFFFFF' },
  planDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: sky,
  },
  whiteDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  selectedPanel: {
    borderRadius: 18,
    padding: Spacing.three,
    gap: Spacing.three,
    borderWidth: 1,
    borderColor: skyBorder,
  },
  selectedPanelHeader: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  smallDangerButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: Spacing.three,
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
  },
  searchInput: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: Spacing.three,
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  searchGrow: { flex: 1 },
  filterButton: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.one,
  },
  filterWrap: {
    position: 'relative',
    zIndex: 5,
  },
  filterMenu: {
    position: 'absolute',
    top: 52,
    right: 0,
    minWidth: 164,
    borderWidth: 1,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#0369A1',
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  filterOption: {
    minHeight: 44,
    paddingHorizontal: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  dressGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.three,
  },
  dressCard: {
    width: '47%',
    gap: Spacing.two,
    position: 'relative',
  },
  dressImage: {
    width: '100%',
    aspectRatio: 4 / 5,
    borderRadius: 16,
    backgroundColor: skySoft,
  },
  paginationRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  pageButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dressMenuButton: {
    position: 'absolute',
    right: Spacing.two,
    top: Spacing.two,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0369A1',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  dressOptionsMenu: {
    position: 'absolute',
    right: Spacing.two,
    top: 44,
    minWidth: 156,
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: Spacing.one,
    zIndex: 3,
    elevation: 5,
  },
  dressOptionRow: {
    minHeight: 38,
    paddingHorizontal: Spacing.two,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.one,
  },
  deleteText: { color: '#E43D12' },
  floatingMenu: {
    position: 'absolute',
    left: Spacing.three,
    right: Spacing.three,
    bottom: Spacing.three,
    alignSelf: 'center',
    maxWidth: MaxContentWidth - Spacing.three * 2,
    minHeight: 58,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.one,
    borderWidth: 1,
    borderColor: skyBorder,
    shadowColor: '#0369A1',
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  menuButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.half,
  },
  activeMenuButton: { backgroundColor: sky },
  menuLabel: {
    fontSize: 10,
    lineHeight: 14,
  },
  activeMenuLabel: { color: '#FFFFFF' },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(31, 31, 31, 0.36)',
  },
  modalSheet: {
    maxHeight: '94%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
    paddingBottom: BottomTabInset + Spacing.three,
    gap: Spacing.two,
  },
  modalHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: skyBorder,
    alignSelf: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.three,
  },
  modalList: { gap: Spacing.three },
  modalDressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    minHeight: 76,
  },
  modalDressImage: {
    width: 58,
    height: 72,
    borderRadius: 14,
    backgroundColor: skySoft,
  },
  modalDressName: { flex: 1 },
  modalActions: {
    flexDirection: 'row',
    gap: Spacing.three,
  },
  modalActionButton: {
    flex: 1,
    paddingHorizontal: Spacing.two,
  },
  imagePreviewBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.three,
    backgroundColor: 'rgba(7, 19, 31, 0.82)',
  },
  imagePreviewSheet: {
    width: '100%',
    height: '82%',
    maxWidth: 640,
    position: 'relative',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
  },
  imagePreviewClose: {
    position: 'absolute',
    top: Spacing.two,
    right: Spacing.two,
    zIndex: 2,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadPreview: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: skySoft,
  },
  uploadForm: {
    gap: Spacing.three,
    paddingBottom: Spacing.two,
  },
  categoryDropdown: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  categoryMenu: {
    borderWidth: 1,
    borderColor: skyBorder,
    borderRadius: 14,
    overflow: 'hidden',
  },
  categoryOption: {
    minHeight: 46,
    paddingHorizontal: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  radioList: { gap: Spacing.two },
  radioRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: sky,
  },
  categoryPills: {
    flexDirection: 'row',
    gap: Spacing.two,
  },
  categoryPill: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: Spacing.three,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryPillActive: {
    backgroundColor: sky,
    borderColor: sky,
  },
});
